// Generated by CoffeeScript 1.7.1
(function() {
  var func_user, md5;

  func_user = require('./../functions/user.coffee');

  md5 = require('MD5');

  module.exports = function(req, res, next) {
    var p, result, token, uid;
    result = {
      success: 0
    };
    if (req.cookies._p) {
      p = req.cookies._p.split(':');
      if (p.length === 2) {
        uid = p[0];
        token = p[1];
        return func_user.getById(uid, function(error, user) {
          if (user) {
            if (md5(user.weibo_token) === token) {
              res.locals.user = user;
              return next();
            } else {
              result.success = 0;
              result.isnotlogin = 1;
              return res.send(result);
            }
          } else {
            result.success = 0;
            result.isnotlogin = 1;
            return res.send(result);
          }
        });
      } else {
        result.success = 0;
        result.isnotlogin = 1;
        return res.send(result);
      }
    } else {
      result.success = 0;
      result.isnotlogin = 1;
      return res.send(result);
    }
  };

}).call(this);
