// Generated by CoffeeScript 1.7.1
(function() {
  var Changefiles, func;

  Changefiles = new __BaseModel("f2e_changefiles");

  Changefiles.sync();

  func = new __BaseFunction(Changefiles);

  func.updateByPath = function(path, data, callback) {
    return Changefiles.find({
      where: {
        path: path
      }
    }).success(function(file) {
      var fields, k, v;
      if (file) {
        fields = [];
        for (k in data) {
          v = data[k];
          if (Changefiles.rawAttributes[k]) {
            fields.push(k);
          }
        }
        return file.updateAttributes(data, fields).success(function() {
          return callback && callback(null, file);
        }).error(function(error) {
          return callback && callback(error);
        });
      } else {
        return callback(new Error('不存在的文件'));
      }
    }).error(function(error) {
      return callback(error);
    });
  };

  func.getByPath = function(path, callback) {
    return Changefiles.find({
      where: {
        path: path
      }
    }).success(function(file) {
      return callback(null, file);
    }).error(function(error) {
      return callback(error);
    });
  };

  module.exports = func;

}).call(this);
