// Generated by CoffeeScript 1.7.1
(function() {
  var User, cache, func_user, pinyin;

  User = __M('f2e_users');

  User.sync();

  pinyin = require('./../lib/PinYin.js');

  cache = {
    allNames: {
      data: [],
      time: 0
    }
  };

  func_user = {
    getAllNames: function(callback) {
      var nowTime;
      nowTime = new Date().getTime();
      if (nowTime - cache.allNames.time > 1000 * 60 * 60) {
        return User.findAll({
          order: 'nick'
        }).success(function(users) {
          var us;
          us = [];
          users.forEach(function(user) {
            return us.push({
              id: user.id,
              nick: user.nick,
              head_pic: user.head_pic,
              pinyin: pinyin(user.nick, {
                style: pinyin.STYLE_NORMAL
              }).join("")
            });
          });
          cache.allNames.data = us;
          cache.allNames.time = nowTime;
          return callback(null, us);
        }).error(function(e) {
          return callback(null, []);
        });
      } else {
        return callback(null, cache.allNames.data);
      }
    },
    getByUserIds: function(ids, callback) {
      return User.findAll({
        where: {
          id: ids
        }
      }).success(function(users) {
        return callback(null, users);
      }).error(function(error) {
        return callback(error);
      });
    },
    getByWeiboId: function(id, callback) {
      return User.find({
        where: {
          weibo_id: id
        }
      }).success(function(user) {
        return callback(null, user);
      }).error(function(error) {
        return callback(error);
      });
    },
    getByNick: function(nick, callback) {
      return User.find({
        where: {
          nick: nick
        }
      }).success(function(user) {
        if (!user) {
          return callback(new Error('不存在的用户昵称'));
        } else {
          return callback(null, user);
        }
      }).error(function(error) {
        return callback(error);
      });
    }
  };

  __FC(func_user, User, ['update', 'count', 'delete', 'getById', 'getAll', 'add']);

  module.exports = func_user;

}).call(this);
