// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    nick: "varchar(255)",
    head_pic: "varchar(255)",
    weibo_id: {
      type: "bigint",
      "private": true
    },
    weibo_token: {
      type: "varchar(100)",
      "private": true
    },
    weibo_refresh: {
      type: "varchar(100)",
      "private": true
    },
    card_id: {
      type: "int",
      "private": true
    },
    coin: {
      type: "int",
      defaultValue: 0
    },
    is_admin: {
      defaultValue: 0,
      type: "tinyint",
      "private": true
    },
    sex: "varchar(5)",
    weibo_name: "varchar(50)",
    desc: "varchar(300)",
    bi: {
      type: "int",
      defaultValue: 5,
      "private": true
    },
    email: {
      type: "varchar(100)",
      "private": true
    },
    is_block: {
      "private": true,
      type: "tinyint",
      defaultValue: 0
    },
    uuid: "varchar(40)"
  };

}).call(this);
