// Generated by CoffeeScript 1.7.1
(function() {
  module.exports.controllers = {
    "/lottery": {
      "get": function(req, res, next) {
        return res.render('cheniu/index.jade');
      }
    }
  };

}).call(this);
