// Generated by CoffeeScript 1.7.1
(function() {
  module.exports.controllers = {
    "/": {
      get: function(req, res, next) {
        return res.render('docs/index.jade');
      }
    }
  };

}).call(this);
