// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    id: {
      type: "int",
      autoIncrement: true,
      primaryKey: true
    },
    page_x: "int",
    page_y: "int",
    element_id: "varchar(20)",
    page_url: "varchar(300)",
    refer_url: "varchar(300)",
    user_phone: "varchar(11)",
    user_tag: "varchar(20)",
    user_ip: "varchar(20)",
    user_agent: "varchar(200)",
    user_screenwidth: "int",
    user_screenheight: "int",
    user_viewwidth: "int",
    user_viewheight: "int"
  };

}).call(this);
