// Generated by CoffeeScript 1.7.1
(function() {
  var Clicks, func;

  Clicks = new __BaseModel("performance/clicks");

  Clicks.sync();

  func = new __BaseFunction(Clicks);

  module.exports = func;

}).call(this);
