// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    cutByte: function(str, num) {
      var i, len, newStr;
      len = 0;
      i = 0;
      newStr = str;
      while (i < str.length) {
        if (str[i].match(/[^\x00-\xff]/g) != null) {
          len += 2;
        } else {
          len += 1;
        }
        i++;
        if (len >= num) {
          newStr = str.substring(0, num) + "…";
        }
      }
      return newStr;
    },
    cutByteAgainst: function(str, num) {
      var i, len, newStr;
      len = 0;
      i = 0;
      newStr = str;
      while (i < str.length) {
        if (str[i].match(/[^\x00-\xff]/g) != null) {
          len += 1;
        } else {
          len += 2;
        }
        i++;
        if (len >= num) {
          newStr = str.substring(0, num) + "…";
        }
      }
      return newStr;
    },
    cut: function(str, num) {
      if (str.length > num) {
        return str.substr(0, num) + "...";
      } else {
        return str;
      }
    }
  };

}).call(this);
