// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = {
    randomItem: function(arr) {
      var l;
      l = arr.length;
      return arr[Math.floor(Math.random() * l)];
    }
  };

}).call(this);
